version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: temp
      MYSQL_USER: admin
      MYSQL_PASSWORD: root

  my-spring-app:
    image: my-temp-app
    ports:
      - 5000:5000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/temp?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db